# Generated by Django 4.2.1 on 2023-05-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(default='path/to/default/image.jpg', max_length=255),
        ),
    ]
