# Generated by Django 4.2.1 on 2023-05-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
